# Generated by Django 6.0.4 on 2026-04-30 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('external_id', models.CharField(blank=True, max_length=160, verbose_name='ID externo')),
                ('title', models.CharField(max_length=500, verbose_name='título')),
                ('normalized_title', models.CharField(max_length=500, verbose_name='título normalizado')),
                ('offer_hash', models.CharField(max_length=64, unique=True, verbose_name='hash da oferta')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço atual')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço original')),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='desconto (%)')),
                ('product_url', models.URLField(max_length=1200, verbose_name='URL do produto')),
                ('affiliate_url', models.URLField(blank=True, max_length=1200, verbose_name='URL de afiliado')),
                ('image_url', models.URLField(blank=True, max_length=1200, verbose_name='URL da imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='payload bruto')),
                ('first_seen_at', models.DateTimeField(verbose_name='visto primeiro em')),
                ('last_seen_at', models.DateTimeField(verbose_name='visto por último em')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='marketplaces.marketplace', verbose_name='marketplace')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'ordering': ['-discount_pct', 'title'],
                'indexes': [models.Index(fields=['offer_hash'], name='offers_offe_offer_h_b0ea81_idx'), models.Index(fields=['marketplace', 'external_id'], name='offers_offe_marketp_0c5b32_idx'), models.Index(fields=['is_active', 'discount_pct'], name='offers_offe_is_acti_f5b4de_idx'), models.Index(fields=['last_seen_at'], name='offers_offe_last_se_7a05d2_idx')],
            },
        ),
    ]
