# Generated by Django 4.2.11 on 2026-05-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='affiliate_url_override',
            field=models.URLField(blank=True, help_text='Link manual opcional, como amzn.to ou amzlink.to. Tem prioridade sobre a URL automática.', max_length=1200, verbose_name='URL de afiliado manual'),
        ),
        migrations.AddField(
            model_name='offer',
            name='asin',
            field=models.CharField(blank=True, db_index=True, help_text='ASIN extraído da URL Amazon. Obrigatório para ofertas Amazon compliance.', max_length=20, verbose_name='ASIN'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_collected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='preço coletado em'),
        ),
        migrations.AddField(
            model_name='offer',
            name='short_description',
            field=models.TextField(blank=True, help_text='Descrição original em pt-BR para a página pública. Nunca copie texto literal da Amazon.', verbose_name='descrição curta'),
        ),
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador público da oferta no site.', max_length=220, null=True, unique=True, verbose_name='slug público'),
        ),
    ]
