# Generated by Django 4.2.11 on 2026-06-04 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_backfill_compliance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.SlugField(help_text='Identificador estável usado pelo classificador e por configurações.', max_length=60, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('weight', models.PositiveSmallIntegerField(default=5, help_text='Peso 1–10. Quanto maior, maior a prioridade na curadoria.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='peso')),
                ('is_test_controlled', models.BooleanField(default=False, help_text='Categoria com exposição limitada (ex: suplementos por viés do dono).', verbose_name='teste controlado')),
                ('exposure_quota_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Cota inicial sugerida da fatia de publicação. Usado a partir do controle de exposição.', max_digits=5, null=True, verbose_name='cota de exposição (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='category_source',
            field=models.CharField(blank=True, help_text='Como a categoria foi atribuída (ex: keyword:title, hint:source_label, fallback:outros, manual).', max_length=60, verbose_name='origem da classificação'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offers.category', verbose_name='categoria'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['category'], name='offers_offe_categor_e44cc5_idx'),
        ),
    ]
