# Generated by Django 4.2.11 on 2026-06-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, help_text='Número de avaliações exibido na listagem do marketplace.', null=True, verbose_name='quantidade de avaliações'),
        ),
        migrations.AddField(
            model_name='offer',
            name='review_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota média (0–5) extraída da listagem do marketplace, quando disponível.', max_digits=3, null=True, verbose_name='nota média'),
        ),
    ]
