# Generated by Django 4.2.11 on 2026-06-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_add_review_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category_source',
            field=models.CharField(blank=True, default='', help_text='Como a categoria foi atribuída (ex: keyword:title, hint:source_label, fallback:outros, manual).', max_length=60, verbose_name='origem da classificação'),
        ),
    ]
