# Generated by Django 6.0.4 on 2026-07-21 07:30
# Sprint 5 - Tarefa 5.1 (achado P8): campo aditivo para dedup por produto canônico.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_fix_category_source_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='produto_canonico_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    'Identificador best-effort do produto físico, usado para dedup interna na '
                    'curadoria (Sprint 5 / achado P8). Amazon usa o ASIN (exato). Mercado Livre e '
                    'Shopee não têm GTIN disponível no payload: Shopee usa o itemId (sem o '
                    'shopId, pois o mesmo item pode ter vários vendedores); Mercado Livre cai '
                    'para o external_id do próprio anúncio (limitação conhecida — não deduplica '
                    'o mesmo produto vendido por lojistas diferentes). Calculado em '
                    'apps.offers.services.normalizer.'
                ),
                max_length=200,
                verbose_name='produto canônico',
            ),
        ),
    ]
