# Generated by Django 6.0.4 on 2026-07-21 07:30
# Sprint 5 - Tarefa 5.2 (achado F / H5; RESTR-05): histórico de preço interno,
# usado só para pontuar a curadoria — nunca publicado.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_offer_produto_canonico_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço')),
                ('collected_at', models.DateTimeField(verbose_name='coletado em')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='offers.offer', verbose_name='oferta')),
            ],
            options={
                'verbose_name': 'histórico de preço',
                'verbose_name_plural': 'histórico de preços',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['offer', 'collected_at'], name='offers_pric_offer_i_ff067a_idx')],
            },
        ),
    ]
