# Generated by Django 6.0.4 on 2026-04-30 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('started_at', models.DateTimeField(verbose_name='iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Sucesso'), ('partial_failed', 'Falha parcial'), ('failed', 'Falhou')], default='running', max_length=30, verbose_name='status')),
                ('total_collected', models.PositiveIntegerField(default=0, verbose_name='total coletado')),
                ('total_valid', models.PositiveIntegerField(default=0, verbose_name='total válido')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scraping_runs', to='marketplaces.marketplace', verbose_name='marketplace')),
            ],
            options={
                'verbose_name': 'execução de coleta',
                'verbose_name_plural': 'execuções de coleta',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='scraping_sc_status_dc264e_idx'), models.Index(fields=['marketplace', 'started_at'], name='scraping_sc_marketp_dc7c8f_idx')],
            },
        ),
    ]
