# Generated by Django 6.0.4 on 2026-04-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('key', models.SlugField(max_length=120, unique=True, verbose_name='chave')),
                ('value', models.TextField(verbose_name='valor')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configurações',
                'ordering': ['key'],
            },
        ),
    ]
