# Generated by Django 6.0.4 on 2026-07-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0005_alter_delivery_delivery_status'),
        ('offers', '0007_fix_category_source_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='status')),
                ('mode', models.CharField(choices=[('shadow', 'Shadow'), ('dry_run', 'Dry-run'), ('homolog', 'Homologação'), ('production', 'Produção')], default='dry_run', max_length=20, verbose_name='modo')),
                ('profile_name', models.CharField(blank=True, max_length=120, verbose_name='profile Hermes')),
                ('model_provider', models.CharField(blank=True, max_length=120, verbose_name='provider do modelo')),
                ('model_name', models.CharField(blank=True, max_length=160, verbose_name='modelo')),
                ('candidate_count', models.PositiveIntegerField(default=0, verbose_name='candidatas')),
                ('selected_count', models.PositiveIntegerField(default=0, verbose_name='selecionadas')),
                ('target_distribution_json', models.JSONField(blank=True, default=dict, verbose_name='distribuição alvo')),
                ('actual_distribution_json', models.JSONField(blank=True, default=dict, verbose_name='distribuição real')),
                ('observer_context_json', models.JSONField(blank=True, default=dict, verbose_name='contexto observer')),
                ('baseline_summary_json', models.JSONField(blank=True, default=dict, verbose_name='baseline')),
                ('input_json_path', models.CharField(blank=True, max_length=500, verbose_name='JSON de entrada')),
                ('output_json_path', models.CharField(blank=True, max_length=500, verbose_name='JSON de saída')),
                ('public_json_path', models.CharField(blank=True, max_length=500, verbose_name='JSON público')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('schema_version', models.CharField(default='1.0', max_length=20, verbose_name='versão schema')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curation_runs', to='distribution.socialchannel', verbose_name='canal')),
            ],
            options={
                'verbose_name': 'execução de curadoria IA',
                'verbose_name_plural': 'execuções de curadoria IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('marketplace_code', models.CharField(blank=True, max_length=64, verbose_name='marketplace')),
                ('baseline_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='score baseline')),
                ('baseline_classification', models.CharField(blank=True, max_length=60, verbose_name='classificação baseline')),
                ('baseline_decision', models.CharField(blank=True, max_length=60, verbose_name='decisão baseline')),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='score IA')),
                ('ai_classification', models.CharField(choices=[('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('improper', 'Imprópria'), ('needs_image_review', 'Requer análise de imagem')], default='rejected', max_length=30, verbose_name='classificação IA')),
                ('conversion_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('discount_quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('audience_fit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('decision_reason', models.TextField(blank=True, verbose_name='motivo')),
                ('risk_flags_json', models.JSONField(blank=True, default=list, verbose_name='riscos')),
                ('observer_signals_json', models.JSONField(blank=True, default=dict, verbose_name='sinais observer')),
                ('title_original', models.CharField(blank=True, max_length=500, verbose_name='título original')),
                ('title_rewritten', models.CharField(blank=True, max_length=500, verbose_name='título reescrito')),
                ('caption_rewritten', models.TextField(blank=True, verbose_name='caption reescrita')),
                ('image_analysis_json', models.JSONField(blank=True, default=dict, verbose_name='análise de imagem')),
                ('blacklist_terms_json', models.JSONField(blank=True, default=list, verbose_name='termos blacklist')),
                ('raw_ai_json', models.JSONField(blank=True, default=dict, verbose_name='JSON bruto IA')),
                ('is_selected_for_batch', models.BooleanField(default=False, verbose_name='selecionada para lote')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curation_decisions', to='offers.offer', verbose_name='oferta')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='curation.curationrun', verbose_name='execução')),
            ],
            options={
                'verbose_name': 'decisão de curadoria IA',
                'verbose_name_plural': 'decisões de curadoria IA',
                'ordering': ['run', '-is_selected_for_batch', '-ai_score', 'offer_id'],
            },
        ),
        migrations.CreateModel(
            name='CurationBlacklistTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('term', models.CharField(max_length=160, verbose_name='termo')),
                ('normalized_term', models.CharField(db_index=True, max_length=160, verbose_name='termo normalizado')),
                ('source', models.CharField(choices=[('ai_image_moderation', 'Moderação IA de imagem'), ('ai_text_moderation', 'Moderação IA de texto')], max_length=40, verbose_name='origem')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('rolled_back', 'Revertido')], default='active', max_length=20, verbose_name='status')),
                ('added_to_setting_at', models.DateTimeField(blank=True, null=True, verbose_name='adicionado ao Setting em')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True, verbose_name='rollback em')),
                ('rollback_reason', models.TextField(blank=True, verbose_name='motivo rollback')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_blacklist_terms', to='offers.offer')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_terms', to='curation.curationdecision')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_terms', to='curation.curationrun')),
            ],
            options={
                'verbose_name': 'termo automático de blacklist',
                'verbose_name_plural': 'termos automáticos de blacklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuratedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronto'), ('consuming', 'Consumindo'), ('sent', 'Enviado'), ('expired', 'Expirado'), ('failed', 'Falhou')], default='draft', max_length=20, verbose_name='status')),
                ('batch_size', models.PositiveIntegerField(default=0, verbose_name='tamanho do lote')),
                ('target_distribution_json', models.JSONField(blank=True, default=dict, verbose_name='distribuição alvo')),
                ('actual_distribution_json', models.JSONField(blank=True, default=dict, verbose_name='distribuição real')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumido em')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curated_batches', to='distribution.socialchannel', verbose_name='canal')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='curation.curationrun', verbose_name='execução')),
            ],
            options={
                'verbose_name': 'lote curado',
                'verbose_name_plural': 'lotes curados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuratedBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('position', models.PositiveIntegerField(verbose_name='posição')),
                ('final_title', models.CharField(max_length=500, verbose_name='título final')),
                ('final_caption_whatsapp', models.TextField(blank=True, verbose_name='caption WhatsApp')),
                ('final_caption_telegram', models.TextField(blank=True, verbose_name='caption Telegram')),
                ('final_image_url', models.URLField(blank=True, max_length=1200, verbose_name='URL imagem final')),
                ('local_image_path', models.CharField(blank=True, max_length=500, verbose_name='imagem local')),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('image_mime_type', models.CharField(blank=True, max_length=80)),
                ('send_status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], default='pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curation.curatedbatch', verbose_name='lote')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_batch_items', to='distribution.delivery', verbose_name='entrega')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curated_batch_items', to='offers.offer', verbose_name='oferta')),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch_item', to='curation.curationdecision', verbose_name='decisão')),
            ],
            options={
                'verbose_name': 'item de lote curado',
                'verbose_name_plural': 'itens de lote curado',
                'ordering': ['batch', 'position'],
                'indexes': [models.Index(fields=['batch', 'send_status'], name='curation_cu_batch_i_595a6c_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'position'), name='unique_curated_batch_position'), models.UniqueConstraint(fields=('batch', 'offer'), name='unique_curated_batch_offer')],
            },
        ),
        migrations.AddIndex(
            model_name='curationrun',
            index=models.Index(fields=['channel', 'status', 'mode'], name='curation_cu_channel_ba6bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='curationrun',
            index=models.Index(fields=['created_at'], name='curation_cu_created_de604f_idx'),
        ),
        migrations.AddIndex(
            model_name='curationdecision',
            index=models.Index(fields=['run', 'ai_classification', 'is_selected_for_batch'], name='curation_cu_run_id_de0c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='curationdecision',
            index=models.Index(fields=['offer', 'created_at'], name='curation_cu_offer_i_68cf2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='curationdecision',
            constraint=models.UniqueConstraint(fields=('run', 'offer'), name='unique_curation_decision_run_offer'),
        ),
        migrations.AddIndex(
            model_name='curationblacklistterm',
            index=models.Index(fields=['status', 'source'], name='curation_cu_status_ae00cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='curationblacklistterm',
            constraint=models.UniqueConstraint(fields=('normalized_term', 'status'), name='unique_curation_blacklist_term_status'),
        ),
        migrations.AddIndex(
            model_name='curatedbatch',
            index=models.Index(fields=['channel', 'status', 'expires_at'], name='curation_cu_channel_36a539_idx'),
        ),
    ]
