"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.db.backends.signals import connection_created

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / 'data'
DATA_DIR.mkdir(exist_ok=True)
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$k5_iwy1)-(2)&p0*w5qx9p2mz(npagl(eo9j*xinhlk&kn9u2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

PUBLIC_SITE_BASE_URL = os.environ.get(
    'PUBLIC_SITE_BASE_URL',
    'https://descontos-bot.vercel.app',
)
AMAZON_AFFILIATE_TAG = os.environ.get(
    'AMAZON_AFFILIATE_TAG',
    os.environ.get('AMAZON_ASSOCIATE_TAG', 'descontos.bot-20'),
)
OFFERS_EXPORT_PATH = os.environ.get(
    'OFFERS_EXPORT_PATH',
    str(DATA_DIR / 'exports' / 'offers.json'),
)
OFFERS_JSON_OUTPUT_PATH = os.environ.get(
    'OFFERS_JSON_OUTPUT_PATH',
    str(BASE_DIR / 'site' / 'offers.json'),
)
SITE_PUBLIC_DIR = os.environ.get(
    'SITE_PUBLIC_DIR',
    str(BASE_DIR / 'site'),
)
SITE_REPO_LOCAL_PATH = os.environ.get(
    'SITE_REPO_LOCAL_PATH',
    str(BASE_DIR),
)
PUBLISH_OFFERS_AFTER_CAPTURE = os.environ.get(
    'PUBLISH_OFFERS_AFTER_CAPTURE',
    'true',
).lower() in ('1', 'true', 'yes', 'on')
PUBLISH_OFFERS_PUSH = os.environ.get(
    'PUBLISH_OFFERS_PUSH',
    'true',
).lower() in ('1', 'true', 'yes', 'on')
PUBLISH_OFFERS_BRANCH = os.environ.get(
    'PUBLISH_OFFERS_BRANCH',
    os.environ.get('SITE_REPO_BRANCH', 'main'),
)
SITE_REPO_BRANCH = PUBLISH_OFFERS_BRANCH
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.marketplaces',
    'apps.offers',
    'apps.distribution',
    'apps.scraping',
    'apps.panel',
    'apps.curation',
    'apps.orchestration',
    'apps.social_posts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'descontos_bot.db',
    }
}


def configure_sqlite_connection(sender, connection, **kwargs):
    if connection.vendor != 'sqlite':
        return

    with connection.cursor() as cursor:
        cursor.execute('PRAGMA foreign_keys=ON')
        cursor.execute('PRAGMA journal_mode=WAL')


connection_created.connect(configure_sqlite_connection)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'bot_file': {
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'bot.log',
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'apps': {
            'handlers': ['console', 'bot_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
