# Generated by Django 6.0.4 on 2026-08-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0006_delivery_next_retry_at_delivery_retry_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('candidate_hash', models.CharField(max_length=64)),
                ('marketplace', models.CharField(max_length=40)),
                ('activation_code', models.CharField(blank=True, max_length=160)),
                ('activation_method', models.CharField(blank=True, max_length=160)),
                ('benefit', models.CharField(blank=True, max_length=500)),
                ('minimum_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('restrictions', models.JSONField(blank=True, default=list)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=1500)),
                ('campaign_url', models.URLField(blank=True, max_length=1500)),
                ('destination_url', models.URLField(max_length=1500)),
                ('affiliate_url', models.URLField(blank=True, max_length=1500)),
                ('evidence', models.TextField(blank=True)),
                ('source_confidence', models.CharField(default='low', max_length=30)),
                ('validation_status', models.CharField(default='pending', max_length=30)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CouponRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('run_key', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('sources_json', models.JSONField(blank=True, default=list)),
                ('observer_pattern_json', models.JSONField(blank=True, default=dict)),
                ('candidates_found', models.PositiveIntegerField(default=0)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                ('errors_json', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouponDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('classification', models.CharField(max_length=20)),
                ('selected', models.BooleanField(default=False)),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('benefit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reliability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frustration_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField(blank=True)),
                ('whatsapp_post', models.TextField(blank=True)),
                ('telegram_post', models.TextField(blank=True)),
                ('editorial_structure_json', models.JSONField(blank=True, default=dict)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='coupons.couponcandidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='couponcandidate',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='coupons.couponrun'),
        ),
        migrations.CreateModel(
            name='CouponDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('message', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('external_message_id', models.CharField(blank=True, max_length=160)),
                ('error_message', models.TextField(blank=True)),
                ('published_url', models.URLField(blank=True, max_length=1500)),
                ('affiliate_used', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='coupons.couponcandidate')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_deliveries', to='distribution.socialchannel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate', 'channel'), name='unique_coupon_delivery_channel')],
            },
        ),
        migrations.AddIndex(
            model_name='couponcandidate',
            index=models.Index(fields=['marketplace', 'candidate_hash'], name='coupons_cou_marketp_fa9b31_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponcandidate',
            constraint=models.UniqueConstraint(fields=('run', 'candidate_hash'), name='unique_coupon_run_hash'),
        ),
    ]
