# Generated by Django 6.0.4 on 2026-04-30 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='código')),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=30, verbose_name='tipo de canal')),
                ('target', models.CharField(help_text='Nome exato do grupo ou identificador usado pelo serviço de envio.', max_length=255, verbose_name='destino')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='habilitado')),
            ],
            options={
                'verbose_name': 'canal social',
                'verbose_name_plural': 'canais sociais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('delivery_status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], max_length=20, verbose_name='status do envio')),
                ('external_message_id', models.CharField(blank=True, max_length=160, verbose_name='ID externo da mensagem')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='offers.offer', verbose_name='oferta')),
                ('social_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='distribution.socialchannel', verbose_name='canal social')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['delivery_status', 'sent_at'], name='distributio_deliver_ec926c_idx'), models.Index(fields=['social_channel', 'delivery_status'], name='distributio_social__c18a72_idx')],
                'constraints': [models.UniqueConstraint(fields=('offer', 'social_channel'), name='unique_delivery_offer_social_channel')],
            },
        ),
    ]
