# Generated by Django 4.2.11 on 2026-05-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialchannel',
            name='link_strategy',
            field=models.CharField(choices=[('affiliate_direct', 'Afiliado direto'), ('bridge_only', 'Página pública')], default='bridge_only', help_text='Use página pública para canais privados. Afiliado direto somente para fontes cadastradas na Amazon.', max_length=20, verbose_name='estratégia de link'),
        ),
    ]
