# Generated by Django 4.2.11 on 2026-05-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_socialchannel_link_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialchannel',
            name='channel_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('whatsapp_group', 'Grupo de WhatsApp'), ('whatsapp_channel', 'Canal do WhatsApp')], default='whatsapp', max_length=30, verbose_name='tipo de canal'),
        ),
    ]
