# Generated by Django 6.0.4 on 2026-05-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_alter_socialchannel_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialchannel',
            name='channel_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('whatsapp_group', 'Grupo de WhatsApp'), ('whatsapp_channel', 'Canal do WhatsApp'), ('telegram_channel', 'Canal do Telegram')], default='whatsapp', max_length=30, verbose_name='tipo de canal'),
        ),
    ]
