# Generated by Django 6.0.4 on 2026-06-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_alter_socialchannel_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Em envio'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], max_length=20, verbose_name='status do envio'),
        ),
    ]
