# Generated by Django 6.0.4 on 2026-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_alter_delivery_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, help_text='Backoff: a fila de envio só tenta novamente após este horário.', null=True, verbose_name='próxima tentativa em'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de reenvios tentados pela fila de envio (apps.distribution.services.fila_envio).', verbose_name='tentativas'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Em envio'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Ignorado'), ('dead_letter', 'Esgotado (dead-letter)')], max_length=20, verbose_name='status do envio'),
        ),
    ]
