# Generated by Django 6.0.4 on 2026-06-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIntelDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('groups_analyzed', models.PositiveIntegerField(default=0)),
                ('messages_analyzed', models.PositiveIntegerField(default=0)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('recommendations_json', models.JSONField(blank=True, default=list)),
                ('scraper_opportunities_json', models.JSONField(blank=True, default=list)),
                ('site_payload_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ObservedWhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jid', models.CharField(max_length=128, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObservedWhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_message_id', models.CharField(max_length=255)),
                ('sender_hash', models.CharField(max_length=64)),
                ('sent_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('urls', models.JSONField(blank=True, default=list)),
                ('has_image', models.BooleanField(default=False)),
                ('raw_type', models.CharField(blank=True, max_length=64)),
                ('parsed_marketplace', models.CharField(blank=True, max_length=64)),
                ('parsed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parsed_original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parsed_discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('parsed_coupon', models.CharField(blank=True, max_length=80)),
                ('editorial_labels', models.JSONField(blank=True, default=list)),
                ('scraper_hints', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='market_intel.observedwhatsappgroup')),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('group', 'external_message_id'), name='unique_observed_whatsapp_message')],
            },
        ),
    ]
