# Generated by Django 6.0.4 on 2026-08-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_intel', '0002_observer_v2_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedOfferLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=1500)),
                ('marketplace_code', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('resolved', 'Resolvido'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], default='pending', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('resolved_url', models.CharField(blank=True, max_length=1500)),
                ('external_item_id', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('image_url', models.CharField(blank=True, max_length=1500)),
                ('seller', models.CharField(blank=True, max_length=200)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('affiliate_url', models.CharField(blank=True, max_length=1500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_links', to='market_intel.observedwhatsappmessage')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'resolved_at'], name='market_inte_status_2a04ba_idx'), models.Index(fields=['external_item_id'], name='market_inte_externa_3ced40_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'source_url'), name='unique_observed_offer_link')],
            },
        ),
    ]
