# Generated by Django 6.0.4 on 2026-05-26 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0004_alter_socialchannel_channel_type'),
        ('offers', '0003_backfill_compliance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('utm_source', models.CharField(max_length=80, verbose_name='UTM source')),
                ('utm_medium', models.CharField(max_length=80, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(max_length=120, verbose_name='UTM campaign')),
                ('utm_content', models.CharField(blank=True, max_length=120, verbose_name='UTM content')),
                ('clicked_at', models.DateTimeField(verbose_name='clicado em')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='hash do IP')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_events', to='offers.offer', verbose_name='oferta')),
                ('social_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to='distribution.socialchannel', verbose_name='canal social')),
            ],
            options={
                'verbose_name': 'evento de clique',
                'verbose_name_plural': 'eventos de clique',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['offer', 'clicked_at'], name='analytics_c_offer_i_7ef593_idx'), models.Index(fields=['social_channel', 'clicked_at'], name='analytics_c_social__20977a_idx'), models.Index(fields=['utm_source', 'clicked_at'], name='analytics_c_utm_sou_a02d4d_idx'), models.Index(fields=['utm_campaign'], name='analytics_c_utm_cam_827b7a_idx')],
            },
        ),
    ]
