# Generated by Django 6.0.4 on 2026-06-02 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('distribution', '0004_alter_socialchannel_channel_type'),
        ('offers', '0003_backfill_compliance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('source', models.CharField(choices=[('amazon', 'Amazon Associates'), ('mercado_livre', 'Mercado Livre Afiliados')], db_index=True, max_length=32, verbose_name='fonte')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='início do período')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='fim do período')),
                ('raw_filename', models.CharField(blank=True, max_length=255, verbose_name='arquivo original')),
                ('payload_sha256', models.CharField(db_index=True, max_length=64, verbose_name='sha256 do payload')),
                ('rows_imported', models.PositiveIntegerField(default=0, verbose_name='linhas importadas')),
                ('rows_skipped', models.PositiveIntegerField(default=0, verbose_name='linhas ignoradas')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'lote de importação de afiliados',
                'verbose_name_plural': 'lotes de importação de afiliados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('source', models.CharField(choices=[('amazon', 'Amazon Associates'), ('mercado_livre', 'Mercado Livre Afiliados')], db_index=True, max_length=32, verbose_name='fonte')),
                ('subid', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='SubID / Tracking ID')),
                ('report_date', models.DateField(db_index=True, verbose_name='data do relatório')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='cliques')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='conversões')),
                ('revenue_brl', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='receita (R$)')),
                ('commission_brl', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='comissão (R$)')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_conversions', to='offers.offer', verbose_name='oferta')),
                ('social_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_conversions', to='distribution.socialchannel', verbose_name='canal social')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='analytics.affiliateimportbatch', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'conversão de afiliado',
                'verbose_name_plural': 'conversões de afiliados',
                'ordering': ['-report_date', '-commission_brl'],
                'indexes': [models.Index(fields=['source', 'report_date'], name='analytics_a_source_3c40d5_idx'), models.Index(fields=['social_channel', 'report_date'], name='analytics_a_social__4888a0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('social_channel__isnull', False)), fields=('offer', 'social_channel', 'source', 'report_date'), name='uniq_affconv_with_channel'), models.UniqueConstraint(condition=models.Q(('social_channel__isnull', True)), fields=('offer', 'source', 'report_date'), name='uniq_affconv_no_channel')],
            },
        ),
    ]
