# Generated by Django 6.0.4 on 2026-07-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_affiliateimportbatch_affiliateconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateconversion',
            name='source',
            field=models.CharField(choices=[('amazon', 'Amazon Associates'), ('mercado_livre', 'Mercado Livre Afiliados'), ('shopee', 'Shopee Afiliados')], db_index=True, max_length=32, verbose_name='fonte'),
        ),
        migrations.AlterField(
            model_name='affiliateimportbatch',
            name='source',
            field=models.CharField(choices=[('amazon', 'Amazon Associates'), ('mercado_livre', 'Mercado Livre Afiliados'), ('shopee', 'Shopee Afiliados')], db_index=True, max_length=32, verbose_name='fonte'),
        ),
    ]
