# Generated by Django 6.0.4 on 2026-07-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_affiliateconversion_source_and_more'),
        ('distribution', '0006_delivery_next_retry_at_delivery_retry_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaCanalDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data', models.DateField(verbose_name='data')),
                ('membros', models.PositiveIntegerField(help_text='Contagem agregada de membros/seguidores do canal nesta data.', verbose_name='membros/seguidores')),
                ('posts_publicados', models.PositiveIntegerField(blank=True, help_text='Quantos posts/stories saíram neste canal nesta data. Deixe em branco para o painel calcular automaticamente a partir dos envios (Delivery) registrados no dia.', null=True, verbose_name='posts publicados')),
                ('cliques_estimados', models.PositiveIntegerField(blank=True, help_text='Medição indireta/manual — preencher só se houver dado futuro de clique agregado por canal. Não é fonte de clique nova.', null=True, verbose_name='cliques estimados')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metricas_diarias', to='distribution.socialchannel', verbose_name='canal')),
            ],
            options={
                'verbose_name': 'métrica diária de canal',
                'verbose_name_plural': 'métricas diárias de canal',
                'ordering': ['-data', 'canal__name'],
                'indexes': [models.Index(fields=['canal', 'data'], name='analytics_m_canal_i_63ec41_idx')],
                'constraints': [models.UniqueConstraint(fields=('canal', 'data'), name='uniq_metricacanaldiaria_canal_data')],
            },
        ),
    ]
