# Generated by Django 6.0.4 on 2026-08-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_metricacanaldiaria'),
        ('offers', '0009_pricehistoryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLAffiliateSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sale_id', models.CharField(help_text='Identificador do próprio ML — é o que torna a reimportação idempotente.', max_length=64, unique=True, verbose_name='id da venda (ML)')),
                ('sale_date', models.DateField(db_index=True, verbose_name='data da venda')),
                ('product_title', models.CharField(blank=True, max_length=255, verbose_name='produto')),
                ('product_link', models.URLField(blank=True, max_length=500, verbose_name='link do produto')),
                ('external_ref', models.CharField(blank=True, db_index=True, help_text='Vazio quando o link é de catálogo (/p/MLB…), que é outro namespace.', max_length=64, verbose_name='MLB')),
                ('category_name', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='categoria (ML)')),
                ('store_name', models.CharField(blank=True, max_length=120, verbose_name='loja')),
                ('sale_value_brl', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor da venda (R$)')),
                ('sale_units', models.PositiveIntegerField(default=1, verbose_name='unidades')),
                ('commission_brl', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='comissão (R$)')),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='comissão (%)')),
                ('sale_type', models.CharField(blank=True, max_length=32, verbose_name='tipo de venda')),
                ('status', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='status')),
                ('status_detail', models.CharField(blank=True, max_length=255, verbose_name='detalhe do status')),
                ('is_own_purchase', models.BooleanField(db_index=True, default=False, help_text='Compra do dono/família: o ML não paga comissão e a venda não pode contar como receita nem como sinal de mercado.', verbose_name='compra própria')),
                ('own_purchase_source', models.CharField(blank=True, choices=[('', 'não é compra própria'), ('manual', 'marcado à mão'), ('auto_rejected', 'inferido por status REJECTED')], default='', max_length=16, verbose_name='origem da marcação')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_sales', to='analytics.affiliateimportbatch', verbose_name='lote')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_affiliate_sales', to='offers.offer', verbose_name='oferta')),
            ],
            options={
                'verbose_name': 'venda de afiliado ML',
                'verbose_name_plural': 'vendas de afiliado ML',
                'ordering': ['-sale_date', '-commission_brl'],
                'indexes': [models.Index(fields=['sale_date', 'is_own_purchase'], name='analytics_m_sale_da_ba6bbd_idx'), models.Index(fields=['status', 'sale_date'], name='analytics_m_status_16d83c_idx')],
            },
        ),
    ]
