# Generated by Django 6.0.4 on 2026-08-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_mlaffiliatesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricacanaldiaria',
            name='fonte',
            field=models.CharField(choices=[('medido_api', 'medido na API do canal'), ('informado_dono', 'contado e informado pelo dono'), ('estimado', 'estimativa não verificada')], db_index=True, default='estimado', help_text='De onde veio o número. Só medição verificada (API ou contagem do dono) entra na curva do painel.', max_length=20, verbose_name='fonte da contagem'),
        ),
    ]
