# Generated by Django 6.0.4 on 2026-04-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='código')),
                ('base_url', models.URLField(max_length=500, verbose_name='URL base')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('affiliate_enabled', models.BooleanField(default=False, verbose_name='afiliado habilitado')),
            ],
            options={
                'verbose_name': 'marketplace',
                'verbose_name_plural': 'marketplaces',
                'ordering': ['name'],
            },
        ),
    ]
