# Generated by Django 4.2.11 on 2026-05-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='affiliate_tag',
            field=models.CharField(blank=True, help_text='Tag usada para montar links canônicos de afiliado quando aplicável.', max_length=50, verbose_name='tag de afiliado'),
        ),
    ]
