# Generated by Django 6.0.4 on 2026-05-06 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0003_backfill_compliance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('format', models.CharField(choices=[('feed', 'Feed'), ('carousel', 'Carrossel'), ('story', 'Story'), ('reel', 'Reel')], max_length=20, verbose_name='formato')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronto'), ('posted', 'Postado'), ('rejected', 'Rejeitado')], default='draft', max_length=20, verbose_name='status')),
                ('asset_paths', models.JSONField(blank=True, default=list, verbose_name='caminhos dos assets')),
                ('caption', models.TextField(blank=True, verbose_name='legenda')),
                ('sticker_target_url', models.URLField(blank=True, max_length=1200, verbose_name='URL alvo do sticker')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='postado em')),
                ('primary_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_instagram_posts', to='offers.offer', verbose_name='oferta principal')),
                ('related_offers', models.ManyToManyField(blank=True, related_name='related_instagram_posts', to='offers.offer', verbose_name='ofertas relacionadas')),
            ],
            options={
                'verbose_name': 'post Instagram',
                'verbose_name_plural': 'posts Instagram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['format', 'status'], name='social_post_format_5646d3_idx'), models.Index(fields=['posted_at'], name='social_post_posted__2e1914_idx')],
            },
        ),
    ]
