# Generated by Django 6.0.4 on 2026-06-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='instagram_media_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID da mídia no Instagram'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='published_error',
            field=models.TextField(blank=True, verbose_name='erro de publicação'),
        ),
    ]
