# Generated by Django 4.2.11 on 2026-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_posts', '0002_instagrampost_instagram_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='telegram_handoff_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID da mensagem de handoff Telegram'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronto'), ('awaiting_post', 'Aguardando publicação manual'), ('posted', 'Postado'), ('rejected', 'Rejeitado')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
